name: URL Deleter
on:
  issues:
    types:
      - opened
      - edited
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - name: Moderate issues
        uses: tachiyomiorg/issue-moderator-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          auto-close-rules: |
            [
              {
                "type": "title",
                "regex": "((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)",
                "message": "URL does not belong here."
              }
            ]
          auto-close-ignore-label: do-not-autoclose
